USE_SONIC_LIB = no
USE_SYS_GLOBAL_LOG = no
MULTI_PROCESS_SUPPORT_AUDIO = no
USE_SHARE_MEM_IN_AUDIO_RPC = no
USE_AiMultiMic = no
USE_HEAP_REPLACE_STACK = yes
USE_CVITEK_SOFTWARE_AEC = yes
USE_NEXT_SSP_DUAL = yes
USE_SPEED = no
AUD_USE_32BIT_WIDTH = no
USE_AUDIN_DEFAULT_PSIZE = no
USE_PDM_AEC = no
USE_KERNEL_MODE_VQE = no
USE_CVIAUDIO_STATIC = yes
ifeq ($(or ${CONFIG_AUD_DRV_SEL}, ${CONFIG_AUD_RTOS_3A}),y)
CFLAGS += -DUSE_ALIOS_AUD_DRV
endif
