SHELL = /bin/bash

include ../module.param
INCS += -I$(UAPI_INC)

# Add CFLAGS variable with -O3 optimization
CFLAGS += -O3

TARGET_A = $(MW_LIB)/libsys.a
TARGET_SO = $(MW_LIB)/libsys.so

include ../module.mk