SHELL = /bin/bash

include ../module.param

SRCS += platform/common/parse_ini.c

INCS += -I../../include/3rd/
INCS += -I../../include/

TARGET_A = $(MW_LIB)/libsensor.a
TARGET_SO = $(MW_LIB)/libsensor.so

include ../module.mk